module.exports = {
  apps: [
    {
      name: 'api-gateway',
      script: './dist/apps/api-gateway/main.js',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        API_GATEWAY_PORT: 3000,
      },
      error_file: './logs/api-gateway-error.log',
      out_file: './logs/api-gateway-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      shutdown_with_message: true,
      wait_ready: true,
      listen_timeout: 5000,
      kill_timeout: 10000,
    },
    {
      name: 'auth-service',
      script: './dist/apps/auth-service/main.js',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/auth-service-error.log',
      out_file: './logs/auth-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      shutdown_with_message: true,
    },
    {
      name: 'user-service',
      script: './dist/apps/user-service/main.js',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/user-service-error.log',
      out_file: './logs/user-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      shutdown_with_message: true,
    },
    {
      name: 'notification-worker',
      script: './dist/apps/notification-worker/main.js',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/notification-worker-error.log',
      out_file: './logs/notification-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      shutdown_with_message: true,
    },
    {
      name: 'email-worker',
      script: './dist/apps/email-worker/main.js',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/email-worker-error.log',
      out_file: './logs/email-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      shutdown_with_message: true,
    },
  ],

  deploy: {
    production: {
      user: 'ubuntu',
      host: 'api.example.com',
      key: '~/.ssh/id_rsa',
      ref: 'origin/main',
      repo: 'git@github.com:your-org/nestjs-monorepo.git',
      path: '/home/ubuntu/app',
      'post-deploy': 'npm install && npm run build:all && pm2 startOrReload ecosystem.config.js --env production',
      'pre-deploy-local': '',
    },
  },
};
